const LANDMARKS = [
['Buckingham Palace','I am where the British monarch lives and works.','A palace where the monarch lives.', 'palace'],
['London Eye','I am a giant wheel. You can see London from me.','A giant wheel above London.','wheel'],
['The Gherkin','I am a glass building shaped like a long, round vegetable.','A round glass building.','gherkin'],
['Tower of London','I am a historic castle that keeps royal treasures.','A castle with royal treasures.','castle'],
['Tower Bridge','I cross the River Thames. My two towers stand above the water.','A bridge with two towers.','bridge'],
['Royal Guards','We wear red coats and tall black hats. We protect the monarch.','Guards in red coats.','guard'],
['The Shard','I am a very tall glass building with a pointed top.','A tall, pointed glass building.','shard'],
['Beefeaters','We wear dark uniforms with red details. We guard the Tower of London.','Guards at the Tower of London.','beefeater'],
['King Charles III','I am the British king. My first name is Charles.','The British king.','king'],
['Saint Paul Cathedral','I am a cathedral with a huge round dome.','A cathedral with a large dome.','dome'],
['Westminster Abbey','I am a church where British kings and queens are crowned.','A church for royal coronations.','abbey'],
['Big Ben','I am the nickname of the Great Bell.','The famous Great Bell.','clock']
];
const TOPICS=[
{id:'london',title:'London Landmarks',section:'Vocabulary',icon:'♜',desc:'Take a little trip around London.',learn:LANDMARKS.map(x=>x[0]).join(' · ')},
{id:'family',title:'Family Tree',section:'Vocabulary',icon:'♧',desc:'Meet the family. Find the connections.',learn:'mother · father · parents · son · daughter · brother · sister · husband · wife · grandfather · grandmother · grandparents · uncle · aunt · cousin'},
{id:'subject',title:'Subject Pronouns',section:'Grammar',icon:'We',desc:'I, you, he… who is it?',learn:'I · you · he · she · it · we · they'},
{id:'object',title:'Object Pronouns',section:'Grammar',icon:'us',desc:'Practice me, him, her and more.',learn:'me · you · him · her · it · us · them'},
{id:'be',title:'Verb to Be',section:'Grammar',icon:'am',desc:'Small words. Lots of possibilities!',learn:'I am · you are · he is · she is · it is · we are · they are<br>Negative: am not · is not / isn’t · are not / aren’t<br>Questions: Am I? · Are you? · Is he? · Is she? · Is it? · Are we? · Are they?'},
{id:'place',title:'Prepositions of Place',section:'Grammar',icon:'↔',desc:'Where is it? Look and discover.',learn:'in · on · under · next to · between · behind · in front of · near · opposite'}
];
function Q(prompt,answer,choices,visual){return {prompt,answer,choices,visual};}
function rows(list,pool){return list.map(([p,a])=>Q(p,a,pool));}
const SUBJECT=['I','you','he','she','it','we','they'],OBJECT=['me','you','him','her','it','us','them'];
const GAMES=[
{id:'guess',topic:'london',title:'Guess the Landmark',desc:'Look at the picture. Choose its name.',questions:LANDMARKS.map(x=>Q('Which landmark, person or group is this?',x[0],LANDMARKS.map(l=>l[0]),'landmark:'+x[3]))},
{id:'who',topic:'london',title:'Who or What Am I?',desc:'Read a clue. Solve the mystery.',questions:LANDMARKS.map(x=>Q('“'+x[1]+'”',x[0],LANDMARKS.map(l=>l[0])))},
{id:'match',topic:'london',title:'Match the Landmark',desc:'Match each name to its description.',type:'match',questions:LANDMARKS.map(x=>Q(x[0],x[2],[]))},
{id:'tree',topic:'family',title:'Family Tree Quiz',desc:'Use the family tree to find the answer.',questions:[
Q('Who is Emma’s brother?','Tom',['Tom','Jack','Peter'],'tree'),Q('Who is Tom’s mother?','Anna',['Anna','Emily','Lily'],'tree'),Q('Anna is Peter’s ___.','wife',['wife','sister','daughter'],'tree'),Q('Jack is Emily’s ___.','husband',['husband','brother','son'],'tree'),Q('Who is Emma’s father?','Peter',['Peter','Jack','George'],'tree'),Q('Lily is Tom’s ___.','cousin',['cousin','sister','mother'],'tree'),Q('George is Emma’s ___.','grandfather',['grandfather','father','uncle'],'tree'),Q('Mary is Tom’s ___.','grandmother',['grandmother','mother','aunt'],'tree'),Q('Emily is Emma’s ___.','aunt',['aunt','sister','grandmother'],'tree'),Q('Jack is Tom’s ___.','uncle',['uncle','father','brother'],'tree'),Q('Emma is Anna’s ___.','daughter',['daughter','son','mother'],'tree'),Q('Tom is Peter’s ___.','son',['son','daughter','father'],'tree')]},
{id:'relationship',topic:'family',title:'Choose the Relationship',desc:'Read the clue. Find the family word.',questions:[
Q('My mother’s father is my ___.','grandfather',['grandfather','brother','cousin']),Q('My father’s sister is my ___.','aunt',['aunt','daughter','grandmother']),Q('My aunt’s son is my ___.','cousin',['cousin','uncle','brother']),Q('My mother and father are my ___.','parents',['parents','grandparents','cousin']),Q('My parents’ daughter is my ___.','sister',['sister','aunt','mother']),Q('My parents’ son is my ___.','brother',['brother','uncle','father']),Q('My father’s brother is my ___.','uncle',['uncle','son','husband']),Q('My father’s mother is my ___.','grandmother',['grandmother','sister','aunt']),Q('My grandfather and grandmother are my ___.','grandparents',['grandparents','parents','cousin']),Q('My mother is my father’s ___.','wife',['wife','daughter','sister'])]},
{id:'replace-subject',topic:'subject',title:'Replace the Subject',desc:'Choose a pronoun to replace the subject.',questions:rows([
['Peter is my brother. → ___ is my brother.','he'],['The book is interesting. → ___ is interesting.','it'],['Jack and I are at home. → ___ are at home.','we'],['My friends are here. → ___ are here.','they'],['Miss Smith is a teacher. → ___ is a teacher.','she'],['Tom is at school. → ___ is at school.','he'],['Emma is happy. → ___ is happy.','she'],['The dog is here. → ___ is here.','it'],['The boys are on the bus. → ___ are on the bus.','they'],['Mom and I are in London. → ___ are in London.','we']],SUBJECT)},
{id:'pronoun',topic:'subject',title:'Pronoun Challenge',desc:'Choose the pronoun for each person or group.',questions:rows([
['Sarah','she'],['Tom','he'],['the dog','it'],['Tom and Sam','they'],['Mom and I','we'],['the books','they'],['Emma','she'],['Peter','he'],['Speaking about myself','I'],['Speaking directly to a friend','you']],SUBJECT)},
{id:'replace-object',topic:'object',title:'Replace the Object',desc:'Choose the pronoun after the verb.',questions:rows([
['Emma is helping Tom. → Emma is helping ___.','him'],['Can you see Elsa? → Can you see ___?','her'],['Look at the boys. → Look at ___.','them'],['The girl is reading the letter. → The girl is reading ___.','it'],['Mom loves you and me. → Mom loves ___.','us'],['I can see the dog. → I can see ___.','it'],['Dad is helping Emma. → Dad is helping ___.','her'],['Anna is talking to Peter. → Anna is talking to ___.','him'],['The teacher helps the children. → The teacher helps ___.','them'],['Tom helps Emma and me. → Tom helps ___.','us'],['Mom is helping me. → Mom is helping ___.','me'],['I am talking to you. → I am talking to ___.','you']],OBJECT)},
{id:'subject-object',topic:'object',title:'Subject or Object Pronoun?',desc:'Look carefully. Which pronoun fits?',questions:[
Q('Peter is my friend. ___ is funny.','He',['He','Him']),Q('I can see Peter. I can see ___.','him',['he','him']),Q('Sarah is here. ___ is happy.','She',['She','Her']),Q('I am talking to Sarah. I am talking to ___.','her',['she','her']),Q('Tom and I are here. ___ are happy.','We',['We','Us']),Q('Mom helps Tom and me. Mom helps ___.','us',['we','us']),Q('The boys are at school. ___ are here.','They',['They','Them']),Q('I can see the boys. I can see ___.','them',['they','them']),Q('___ am from London.','I',['I','Me']),Q('Can you help ___?','me',['I','me'])]},
{id:'am-is-are',topic:'be',title:'Am / Is / Are',desc:'Fill the gap with am, is or are.',questions:rows([
['London ___ the capital of England.','is'],['I ___ from London.','am'],['They ___ on the bus.','are'],['She ___ happy.','is'],['We ___ at school.','are'],['You ___ in our class.','are'],['He ___ my brother.','is'],['It ___ a book.','is'],['I ___ tired.','am'],['The children ___ here.','are']],['am','is','are'])},
{id:'negative',topic:'be',title:'Make It Negative',desc:'Choose the correct negative sentence.',questions:[
Q('He is hungry.','He isn’t hungry.',['He isn’t hungry.','He aren’t hungry.','He am not hungry.']),Q('They are at school.','They aren’t at school.',['They aren’t at school.','They isn’t at school.','They am not at school.']),Q('I am tired.','I am not tired.',['I am not tired.','I isn’t tired.','I aren’t tired.']),Q('She is happy.','She is not happy.',['She is not happy.','She are not happy.','She am not happy.']),Q('We are on the bus.','We are not on the bus.',['We are not on the bus.','We is not on the bus.','We am not on the bus.']),Q('You are here.','You aren’t here.',['You aren’t here.','You isn’t here.','You am not here.']),Q('It is a book.','It isn’t a book.',['It isn’t a book.','It aren’t a book.','It am not a book.']),Q('Tom is from London.','Tom is not from London.',['Tom is not from London.','Tom are not from London.','Tom am not from London.']),Q('The boys are happy.','The boys aren’t happy.',['The boys aren’t happy.','The boys isn’t happy.','The boys am not happy.']),Q('I am at home.','I am not at home.',['I am not at home.','I is not at home.','I are not at home.'])]},
{id:'question',topic:'be',title:'Make a Question',desc:'Choose the correct question.',questions:[
Q('She is from Wales.','Is she from Wales?',['Is she from Wales?','Are she from Wales?','Am she from Wales?']),Q('They are from England.','Are they from England?',['Are they from England?','Is they from England?','Am they from England?']),Q('You are in our class.','Are you in our class?',['Are you in our class?','Is you in our class?','Am you in our class?']),Q('The teacher is British.','Is the teacher British?',['Is the teacher British?','Are the teacher British?','Am the teacher British?']),Q('I am happy.','Am I happy?',['Am I happy?','Is I happy?','Are I happy?']),Q('He is at home.','Is he at home?',['Is he at home?','Are he at home?','Am he at home?']),Q('It is a dog.','Is it a dog?',['Is it a dog?','Are it a dog?','Am it a dog?']),Q('We are at school.','Are we at school?',['Are we at school?','Is we at school?','Am we at school?']),Q('Tom is here.','Is Tom here?',['Is Tom here?','Are Tom here?','Am Tom here?']),Q('The books are on the table.','Are the books on the table?',['Are the books on the table?','Is the books on the table?','Am the books on the table?'])]},
{id:'where',topic:'place',title:'Where is it?',desc:'Look at the scene. Find the right place word.',questions:['in','on','under','next to','between','behind','in front of','near','opposite'].map(a=>Q(a==='between'?'The ball is ___ the two boxes.':a==='opposite'?'The ball is ___ the box, across the road.':'The ball is ___ the box.',a,['in','on','under','next to','between','behind','in front of','near','opposite'],'position:'+a))},
{id:'map',topic:'place',title:'London Map Challenge',desc:'Explore a fictional map of London.',questions:[
Q('The café is ___ the museum.','next to',['next to','in','under'],'map'),Q('The London Eye is ___ Big Ben, across the road.','opposite',['opposite','in','under'],'map'),Q('The park is ___ the museum.','behind',['behind','under','in'],'map'),Q('The bus stop is ___ the museum.','in front of',['in front of','in','on'],'map'),Q('The museum is ___ the park.','in front of',['in front of','under','in'],'map'),Q('The museum is ___ the café.','next to',['next to','in','on'],'map'),Q('Big Ben is ___ the London Eye, across the road.','opposite',['opposite','under','in'],'map'),Q('The museum is ___ the park and the bus stop.','between',['between','in','on'],'map'),Q('The bus stop is ___ the museum.','near',['near','in','under'],'map'),Q('Buckingham Palace is ___ the London Eye.','next to',['next to','in','under'],'map')]}
];
if(typeof module!=='undefined')module.exports={LANDMARKS,TOPICS,GAMES};
